# DeviceShifu Driver Node Configuration
driver_node_ros1:
  # Speed Parameters
  linear_speed: 0.5  # Linear velocity (m/s)
  angular_speed: 0.2  # Angular velocity (rad/s)
  
  # Camera Parameters
  camera_fps: 30  # Frame rate
  camera_width: 720  # Image width
  camera_height: 480  # Image height
  
  # Simulation Image Parameters
  sim_image_color: [187, 197, 57]  # BGR format of #39c5bb  DeviceShifu Driver Node Configuration